name: "Compare Coverage Diff"
author: "Dimitar Stoimenov"

inputs:
  delta:
    description: "Maximum allowed difference in percentage."
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
