name: "Annotate PR with Typescript errors"
description: "Add comments"
author: "Dimitar Stoimenov"

inputs:
  gh-token:
    description: "The Github token for authentication."
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
